apiVersion: v1
kind: Service
metadata:
  name: app-external
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.app.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    type: app
