apiVersion: v1
kind: Service
metadata:
  name: database-headless
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ip: {{ .Values.db.ip }}
  ports:
    - port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
      protocol: TCP
      name: http
  selector:
    type: db
