apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgress-pvc
  namespace: app
spec:
  storageClassName: standart
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi