- name: Download kubectl binary
  ansible.builtin.get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/v1.25.5/bin/linux/amd64/kubectl"
    checksum: "sha512:c62099f1022f924b8f95ce3adc7588f0b2a3a0194959484b2b7c8b156d4391ae4a6c53e216655a062048f9bf6622c74410d369c979561d260c4e4d4785b525c8"
    dest: "{{ lookup('env', 'TMPDIR') | default('/tmp', true) }}"
    mode: 0600
  tags:
    - kubectl

- name: Copy kubectl binary to destination directory
  ansible.builtin.copy:
    src: "{{ lookup('env', 'TMPDIR') | default('/tmp', true) }}/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: "0775"
    owner: "root"
    group: "root"
    remote_src: true
  with_items:
    - kubectl
    
- name: Download helm installer
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3"  
    dest: "{{ lookup('env', 'TMPDIR') | default('/tmp', true) }}/get_helm.sh"
    mode: 0700
    
- name: Install Helm
  shell: "{{ lookup('env', 'TMPDIR') | default('/tmp', true) }}/get_helm.sh"